import { createHash, randomUUID } from "node:crypto";
import { isProxy } from "node:util/types";
import type { WorkflowRuntimeDatabase, WorkflowRuntimeSqlClient } from "../db/workflow-runtime-store";
import type { ResolvedWorkflowRuntimeTenant } from "../db/workflow-runtime-tenant";
import type { AuthenticatedIdentitySource } from "../composition/authenticated-owner-read-runtime";
// @ts-expect-error Node.js direct TypeScript execution requires the runtime extension.
import { createPostgresWorkflowRuntimeTenantResolver, isResolvedWorkflowRuntimeTenant } from "../db/workflow-runtime-tenant.ts";
// @ts-expect-error Node.js direct TypeScript execution requires the runtime extension.
import { validateAndNormalizeWorkflowRunSnapshot } from "../contracts/workflow-run.ts";
// @ts-expect-error Node.js direct TypeScript execution requires the runtime extension.
import { isProjectKey } from "../projects/project-registry.ts";
// @ts-expect-error Node.js direct TypeScript execution requires the runtime extension.
import { isProjectTaskType, isTaskGoal, isTaskKey, isTaskTitle } from "./project-task.ts";

// AI-038.4a Owner Task MUTATION contract — deliberately separate from the read-only OwnerReadBackend.
//
// Control-plane INTENT only: createTask records a draft task, attachRun records that an existing
// runtime run belongs to a task. Nothing here starts a run, calls a model / provider / executor,
// touches GitHub, commits, pushes or deploys.
//
//   trusted config { database, domainWorkspaceId } + request-scoped identity source
//     → tenant resolved by the trusted resolver (never caller data)
//     → identity: exactly one resolve(), output = untrusted data ({ userId } only)
//     → ONE transaction:
//         Owner authority re-verified with FOR SHARE on user / membership / workspace / role rows
//         (a concurrent revocation waits for this commit or is seen before the write)
//         project row FOR SHARE with the required status (a concurrent pause / archive cannot slip
//         between check and commit)
//         the write + exactly ONE audit event (task.created | task.run_attached)
//
// Every negative outcome is one of three opaque statuses (unauthenticated / unavailable / conflict);
// no SQL, constraint, UUID or reason ever leaves. Task IDs are generated by the server.

export type CreateTaskResult =
  | Readonly<{ status: "created" | "replayed"; task: Readonly<{ taskId: string; projectId: string; status: "draft" }> }>
  | Readonly<{ status: "conflict" | "unavailable" | "unauthenticated" | "invalid_input" }>;

export type AttachRunResult =
  | Readonly<{ status: "attached" | "already_attached"; taskId: string; runId: string }>
  | Readonly<{ status: "conflict" | "unavailable" | "unauthenticated" | "invalid_input" }>;

export interface OwnerTaskMutations {
  createTask(input: unknown): Promise<CreateTaskResult>;
  attachRun(input: unknown): Promise<AttachRunResult>;
}

const stableIdPattern = /^[a-z0-9][a-z0-9._-]{0,63}$/u;
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
const idempotencyKeyPattern = /^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$/u;
const priorities = new Set(["P0", "P1", "P2", "P3", "P4"]);
const risks = new Set(["low", "medium", "high", "critical"]);
const createFields = ["idempotencyKey", "projectId", "title", "goal", "type", "priority", "riskLevel"] as const;
const attachFields = ["taskId", "runId"] as const;

const freeze = <T extends object>(value: T): Readonly<T> => Object.freeze(value);
const outcome = <S extends string>(status: S) => freeze({ status });

// The shared write-boundary primitives below are also used by the AI-039 FeaturePlan revision contract
// (lib/development/feature-plan-mutations.ts); this module itself still writes tasks / links only.
export class Conflict extends Error {}
export class Unavailable extends Error {}

// Own data members of an ordinary non-Proxy object with EXACTLY `fields`; getters never run.
export function exactOwnData(input: unknown, fields: readonly string[]): Record<string, unknown> | null {
  try {
    if (typeof input !== "object" || input === null || isProxy(input) || Array.isArray(input)) return null;
    const prototype = Object.getPrototypeOf(input);
    if (prototype !== Object.prototype && prototype !== null) return null;
    const keys = Reflect.ownKeys(input);
    if (keys.length !== fields.length || keys.some((key) => typeof key !== "string" || !fields.includes(key))) return null;
    const values: Record<string, unknown> = {};
    for (const field of fields) {
      const descriptor = Object.getOwnPropertyDescriptor(input, field);
      if (!descriptor || !Object.hasOwn(descriptor, "value")) return null;
      values[field] = descriptor.value;
    }
    return values;
  } catch {
    return null;
  }
}

export function capturedMethod(input: unknown, name: string): ((...args: unknown[]) => unknown) | null {
  try {
    if (typeof input !== "object" || input === null || isProxy(input) || Array.isArray(input)) return null;
    const descriptor = Object.getOwnPropertyDescriptor(input, name);
    return descriptor && Object.hasOwn(descriptor, "value") && typeof descriptor.value === "function"
      ? descriptor.value as (...args: unknown[]) => unknown
      : null;
  } catch {
    return null;
  }
}

// Only a genuine native Promise is awaited (no arbitrary thenable / Proxy `then` is ever invoked).
export async function resolveUserId(resolve: (...args: unknown[]) => unknown): Promise<string | null> {
  let raw: unknown;
  try {
    raw = Reflect.apply(resolve, undefined, []);
    if (typeof raw === "object" && raw !== null) {
      if (isProxy(raw)) return null;
      if (Object.getPrototypeOf(raw) === Promise.prototype) {
        if (Object.hasOwn(raw, "then") || Object.hasOwn(raw, "constructor")) return null;
        raw = await (raw as Promise<unknown>);
      }
    }
  } catch {
    return null;
  }
  const fields = exactOwnData(raw, ["userId"]);
  const userId = fields?.userId;
  return typeof userId === "string" && uuidPattern.test(userId) ? userId : null;
}

type CreateIntent = Readonly<{
  idempotencyKey: string;
  projectId: string;
  title: string;
  goal: string | null;
  type: string;
  priority: string | null;
  riskLevel: string | null;
}>;

function createIntent(input: unknown): CreateIntent | null {
  const fields = exactOwnData(input, createFields);
  if (!fields) return null;
  const { idempotencyKey, projectId, title, goal, type, priority, riskLevel } = fields;
  if (typeof idempotencyKey !== "string" || !idempotencyKeyPattern.test(idempotencyKey)
    || !isProjectKey(projectId) || !isTaskTitle(title) || !isTaskGoal(goal) || !isProjectTaskType(type)
    || (priority !== null && (typeof priority !== "string" || !priorities.has(priority)))
    || (riskLevel !== null && (typeof riskLevel !== "string" || !risks.has(riskLevel)))) {
    return null;
  }
  return freeze({ idempotencyKey, projectId, title, goal, type, priority, riskLevel }) as CreateIntent;
}

// sha256 over the canonical immutable creation intent (fixed key order; the idempotency key excluded).
export function creationIntentFingerprint(intent: Omit<CreateIntent, "idempotencyKey">): string {
  const canonical = JSON.stringify([intent.projectId, intent.title, intent.goal, intent.type, intent.priority, intent.riskLevel]);
  return createHash("sha256").update(canonical).digest("hex");
}

const isSqlState = (error: unknown): boolean =>
  typeof error === "object" && error !== null && typeof (error as { code?: unknown }).code === "string"
  && /^[0-9A-Z]{5}$/u.test((error as { code: string }).code);

// One transaction on one pooled session, following the AGENTS DB rules: the session is destroyed after
// a failed BEGIN, a COMMIT that did not succeed, a failed ROLLBACK or any non-SQLSTATE error. A COMMIT
// that did not succeed is ambiguous and surfaces as `unavailable` (a retry with the same idempotency
// key is safe). No slow work happens inside the transaction.
export async function inTransaction<T>(database: WorkflowRuntimeDatabase, work: (client: WorkflowRuntimeSqlClient) => Promise<T>): Promise<T> {
  const client = await database.connect();
  let destroy = false;
  try {
    try {
      await client.query("/* task-mutation:begin */ begin");
    } catch {
      destroy = true;
      throw new Unavailable();
    }
    let result: T;
    try {
      result = await work(client);
    } catch (error) {
      if (!isSqlState(error) && !(error instanceof Conflict) && !(error instanceof Unavailable)) destroy = true;
      try {
        await client.query("/* task-mutation:rollback */ rollback");
      } catch {
        destroy = true;
      }
      throw error;
    }
    try {
      await client.query("/* task-mutation:commit */ commit");
    } catch {
      destroy = true;
      throw new Unavailable();
    }
    return result;
  } finally {
    client.release(destroy);
  }
}

// Same Owner predicate as the AI-038.1 read check, here inside the write transaction and with
// FOR SHARE on every authority row so a concurrent revocation is serialized against the write.
export async function lockOwnerAuthority(client: WorkflowRuntimeSqlClient, tenant: ResolvedWorkflowRuntimeTenant, userId: string): Promise<void> {
  const result = await client.query(
    `/* task-mutation:owner-lock */
     select account.id
     from users as account
     join workspace_members as member on member.user_id = account.id and member.workspace_id = $1::uuid
     join workspaces as workspace on workspace.id = member.workspace_id
     join member_role_assignments as assignment on assignment.member_id = member.id
     join roles as role on role.id = assignment.role_id
     where account.id = $2::uuid
       and account.status = 'active'
       and member.status = 'active'
       and workspace.status in ('demo', 'active')
       and role.code = 'owner'
       and (role.workspace_id = $1::uuid or (role.workspace_id is null and role.is_system))
     limit 1
     for share of account, member, workspace, assignment, role`,
    [tenant.workspaceDatabaseId, userId],
  );
  if (result.rowCount !== 1) throw new Unavailable();
}

// Project row FOR SHARE with the required status; a concurrent pause / archive either commits first
// (then the re-evaluated predicate fails here) or waits for this transaction.
async function lockProject(client: WorkflowRuntimeSqlClient, tenant: ResolvedWorkflowRuntimeTenant, projectId: string, statuses: readonly string[]): Promise<void> {
  const result = await client.query(
    `/* task-mutation:project-lock */
     select project_key from projects
     where workspace_id = $1 and project_key = $2 and status = any($3::text[])
     for share`,
    [tenant.workspaceDatabaseId, projectId, [...statuses]],
  );
  if (result.rowCount !== 1) throw new Unavailable();
}

export function createOwnerTaskMutations(input: unknown): OwnerTaskMutations {
  const config = exactOwnData(input, ["database", "domainWorkspaceId", "identitySource"]);
  const connect = config ? capturedMethod(config.database, "connect") : null;
  const resolve = config ? capturedMethod(config.identitySource as AuthenticatedIdentitySource, "resolve") : null;
  const domainWorkspaceId = config?.domainWorkspaceId;
  if (!config || !connect || !resolve || typeof domainWorkspaceId !== "string" || !stableIdPattern.test(domainWorkspaceId)) {
    throw new Error("Owner task mutation configuration is invalid.");
  }
  // Receiver-free, frozen captures: the caller's objects are not retained as authority.
  const database: WorkflowRuntimeDatabase = Object.freeze({
    connect: () => Reflect.apply(connect, undefined, []) as ReturnType<WorkflowRuntimeDatabase["connect"]>,
  });

  // Tenant first (trusted configuration), then the request's identity, exactly once.
  async function authenticate(): Promise<Readonly<{ tenant: ResolvedWorkflowRuntimeTenant; userId: string }> | "unauthenticated" | "unavailable"> {
    if (typeof window !== "undefined") return "unavailable";
    let tenant: ResolvedWorkflowRuntimeTenant | null;
    try {
      tenant = await createPostgresWorkflowRuntimeTenantResolver(database).resolve(domainWorkspaceId);
    } catch {
      tenant = null;
    }
    if (!tenant || !isResolvedWorkflowRuntimeTenant(tenant)) return "unavailable";
    const userId = await resolveUserId(resolve!);
    return userId ? freeze({ tenant, userId }) : "unauthenticated";
  }

  async function createTask(raw: unknown): Promise<CreateTaskResult> {
    const intent = createIntent(raw);
    if (!intent) return outcome("invalid_input");
    const auth = await authenticate();
    if (auth === "unauthenticated" || auth === "unavailable") return outcome(auth);
    const fingerprint = creationIntentFingerprint(intent);
    const taskKey = `task-${randomUUID().replaceAll("-", "").slice(0, 20)}`;
    try {
      return await inTransaction(database, async (client) => {
        await lockOwnerAuthority(client, auth.tenant, auth.userId);
        await lockProject(client, auth.tenant, intent.projectId, ["active"]);
        const inserted = await client.query<{ id: string; task_key: string }>(
          `/* task-mutation:create */
           insert into project_tasks (workspace_id, project_key, task_key, title, goal, task_type, status, priority,
                                      risk_level, created_by, creation_idempotency_key, creation_intent_fingerprint)
           values ($1, $2, $3, $4, $5, $6, 'draft', $7, $8, $9, $10, $11)
           on conflict (workspace_id, creation_idempotency_key) where creation_idempotency_key is not null do nothing
           returning id::text, task_key`,
          [auth.tenant.workspaceDatabaseId, intent.projectId, taskKey, intent.title, intent.goal, intent.type,
            intent.priority, intent.riskLevel, auth.userId, intent.idempotencyKey, fingerprint],
        );
        if (inserted.rowCount === 1) {
          const row = inserted.rows[0];
          await client.query(
            `/* task-mutation:audit-created */
             insert into audit_events (workspace_id, actor_user_id, event_type, entity_type, entity_id, metadata)
             values ($1, $2, 'task.created', 'project_task', $3::uuid, $4::jsonb)`,
            [auth.tenant.workspaceDatabaseId, auth.userId, row.id, JSON.stringify({ taskId: row.task_key, projectId: intent.projectId })],
          );
          return freeze({ status: "created" as const, task: freeze({ taskId: row.task_key, projectId: intent.projectId, status: "draft" as const }) });
        }
        // The key already exists (possibly committed by a concurrent identical request): same intent →
        // the same task, no new audit; anything else → generic conflict.
        const existing = await client.query<{ task_key: string; project_key: string; creation_intent_fingerprint: string; status: string }>(
          `/* task-mutation:create-replay */
           select task_key, project_key, creation_intent_fingerprint, status
           from project_tasks where workspace_id = $1 and creation_idempotency_key = $2`,
          [auth.tenant.workspaceDatabaseId, intent.idempotencyKey],
        );
        if (existing.rowCount !== 1) throw new Unavailable();
        const row = existing.rows[0];
        if (row.creation_intent_fingerprint !== fingerprint || row.project_key !== intent.projectId || !isTaskKey(row.task_key)) throw new Conflict();
        return freeze({ status: "replayed" as const, task: freeze({ taskId: row.task_key, projectId: row.project_key, status: "draft" as const }) });
      });
    } catch (error) {
      return outcome(error instanceof Conflict ? "conflict" : "unavailable");
    }
  }

  async function attachRun(raw: unknown): Promise<AttachRunResult> {
    const fields = exactOwnData(raw, attachFields);
    const taskId = fields?.taskId;
    const runId = fields?.runId;
    if (!isTaskKey(taskId) || typeof runId !== "string" || !stableIdPattern.test(runId)) return outcome("invalid_input");
    const auth = await authenticate();
    if (auth === "unauthenticated" || auth === "unavailable") return outcome(auth);
    try {
      return await inTransaction(database, async (client) => {
        await lockOwnerAuthority(client, auth.tenant, auth.userId);
        const task = await client.query<{ project_key: string }>(
          `/* task-mutation:task-lock */
           select project_key from project_tasks where workspace_id = $1 and task_key = $2 for update`,
          [auth.tenant.workspaceDatabaseId, taskId],
        );
        if (task.rowCount !== 1) throw new Unavailable();
        const projectId = task.rows[0].project_key;
        await lockProject(client, auth.tenant, projectId, ["active", "paused"]);
        // The run row is locked and its FACTUAL snapshot validated before anything is linked: a
        // corrupted denormalized column (project/workflow/status/revision) fails closed.
        const runRow = await client.query<Record<string, unknown>>(
          `/* task-mutation:run-lock */
           select runtime_id, project_id, workflow_id, status, revision::text as revision, runtime_snapshot
           from workflow_runs where workspace_id = $1 and runtime_id = $2
           for share`,
          [auth.tenant.workspaceDatabaseId, runId],
        );
        if (runRow.rowCount !== 1) throw new Unavailable();
        const run = runRow.rows[0];
        const decision = validateAndNormalizeWorkflowRunSnapshot(run.runtime_snapshot);
        const snapshot = decision.normalizedSnapshot;
        if (decision.verdict !== "allow" || !snapshot || snapshot.runId !== run.runtime_id || snapshot.runId !== runId
          || snapshot.projectId !== run.project_id || snapshot.projectId !== projectId
          || snapshot.workflowId !== run.workflow_id || snapshot.status !== run.status
          || String(snapshot.revision) !== run.revision) {
          throw new Unavailable();
        }
        const linked = await client.query<{ id: string }>(
          `/* task-mutation:attach */
           insert into project_task_runs (workspace_id, project_key, task_key, run_id)
           values ($1, $2, $3, $4)
           on conflict (workspace_id, run_id) do nothing
           returning id::text`,
          [auth.tenant.workspaceDatabaseId, projectId, taskId, runId],
        );
        if (linked.rowCount === 1) {
          await client.query(
            `/* task-mutation:audit-attached */
             insert into audit_events (workspace_id, actor_user_id, event_type, entity_type, entity_id, metadata)
             values ($1, $2, 'task.run_attached', 'project_task_run', $3::uuid, $4::jsonb)`,
            [auth.tenant.workspaceDatabaseId, auth.userId, linked.rows[0].id, JSON.stringify({ taskId, runId, projectId })],
          );
          return freeze({ status: "attached" as const, taskId, runId });
        }
        // The run is already linked (the unique key is the last race guard): same task → idempotent.
        const owner = await client.query<{ task_key: string }>(
          `/* task-mutation:attach-replay */
           select task_key from project_task_runs where workspace_id = $1 and run_id = $2`,
          [auth.tenant.workspaceDatabaseId, runId],
        );
        if (owner.rowCount !== 1) throw new Unavailable();
        if (owner.rows[0].task_key !== taskId) throw new Conflict();
        return freeze({ status: "already_attached" as const, taskId, runId });
      });
    } catch (error) {
      return outcome(error instanceof Conflict ? "conflict" : "unavailable");
    }
  }

  return Object.freeze({ createTask, attachRun });
}
