import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

/* eslint-disable @typescript-eslint/no-explicit-any -- adversarial contract fixtures intentionally cross unknown boundaries */

const mockContract = (await import(new URL("../lib/providers/deterministic-mock-model-provider.ts", import.meta.url).href)) as typeof import("../lib/providers/deterministic-mock-model-provider");
const runContract = (await import(new URL("../lib/contracts/workflow-run.ts", import.meta.url).href)) as typeof import("../lib/contracts/workflow-run");
const invocationContract = (await import(new URL("../lib/contracts/model-invocation.ts", import.meta.url).href)) as typeof import("../lib/contracts/model-invocation");
const adapterContract = (await import(new URL("../lib/contracts/model-provider-adapter.ts", import.meta.url).href)) as typeof import("../lib/contracts/model-provider-adapter");

const { createDeterministicMockModelProvider, mockModelProviderLimits } = mockContract;
const { createWorkflowRunSnapshot, evaluateWorkflowRunTransition } = runContract;
const { evaluateModelInvocationAdmission, modelInvocationLimits } = invocationContract;
const { modelProviderAdapterLimits } = adapterContract;

function clone<T>(value: T): T { return structuredClone(value); }
function budget() { return { maxConcurrentRuns: 4, maxAttemptsPerRun: 3, maxRunMinutes: 120, dailyTokenBudget: 1_000_000, monthlyCostBudgetUsdCents: 250_000 }; }
function project() { return { id: "project-one", workspaceId: "workspace-primary", version: 3, name: "Project one", slug: "project-one", summary: "Owner-controlled project context.", kind: "internal_product", status: "active", defaultLocale: "en-US", timeZone: "UTC", dataRegion: "eu", dataClassification: "confidential", goals: ["Operate safely"], nonGoals: ["Autonomous actions"], tags: ["one"], resources: [{ id: "repository-one", kind: "code_repository", label: "Repository one", status: "connected", connectionId: "connection-one", resourceRef: "owner/repository-one", capabilities: ["read_metadata", "propose_change"] }], allowedModelProfileIds: ["model-shared", "model-one"], knowledgeCollectionIds: ["knowledge-one"], policy: { externalActionMode: "approval_required", dataEgressMode: "forbidden", requiredApprovalActions: ["project-review-one"], forbiddenActions: ["Project action forbidden"] }, budget: budget() }; }
function department() { return { id: "department-one", projectId: "project-one", version: 5, code: "development", name: "Department one", summary: "Reviewed work.", status: "active", operatingMode: "approval_gated", goals: ["Build reviewed artifacts"], nonGoals: ["Deploy automatically"], resourceGrants: [{ resourceId: "repository-one", capabilities: ["read_metadata", "propose_change"] }], allowedModelProfileIds: ["model-shared", "model-one"], knowledgeCollectionIds: ["knowledge-one"], enabledWorkflowIds: ["workflow-one"], operatorRoleIds: ["role-owner"], modelRouting: { primaryModelProfileId: "model-shared", fallbackModelProfileIds: ["model-one"], reviewerModelProfileId: "model-one", independentReviewRequired: true }, policy: { externalActionMode: "approval_required", dataEgressMode: "forbidden", additionalRequiredApprovalActions: ["department-review-one"], additionalForbiddenActions: ["Department publish forbidden"] }, budget: { ...budget(), maxConcurrentRuns: 3, maxAttemptsPerRun: 2, maxRunMinutes: 60 } }; }
function binding(kind: "agent" | "workflow") { return { id: `${kind}-binding-one`, projectId: "project-one", departmentId: "department-one", version: kind === "agent" ? 7 : 8, status: "active", kind, subjectId: `${kind}-one`, requestedResources: [{ resourceId: "repository-one", capabilities: ["read_metadata", "propose_change"] }], requestedModelProfileIds: ["model-shared", "model-one"], requestedKnowledgeCollectionIds: ["knowledge-one"], requestedBudget: { ...budget(), maxConcurrentRuns: 1, maxAttemptsPerRun: 2, maxRunMinutes: 30 }, externalActionMode: "approval_required", dataEgressMode: "forbidden", additionalRequiredApprovalActions: [kind === "workflow" ? "workflow-external-one" : "agent-review-one"], additionalForbiddenActions: [`${kind} deploy forbidden`] }; }
function registry() { return { workspaceId: "workspace-primary", projects: [{ projectManifest: project(), departmentManifests: [department()], bindings: [binding("agent"), binding("workflow")] }] }; }
function agent() { return { id: "agent-one", projectId: "project-one", departmentId: "department-one", version: 11, roleCode: "developer", name: "Developer one", summary: "Creates bounded artifacts.", status: "active", instructionProfileId: "instructions-one", goals: ["Create reviewed artifacts"], nonGoals: ["Deploy automatically"], outputTypes: ["patch", "test_report"], allowedWorkflowIds: ["workflow-one"], allowedToolIds: ["tool-read"], allowedModelProfileIds: ["model-shared", "model-one"], knowledgeCollectionIds: ["knowledge-one"], modelRouting: { primaryModelProfileId: "model-shared", fallbackModelProfileIds: ["model-one"], reviewerModelProfileId: "model-one", independentReviewRequired: true }, additionalRequiredApprovalActions: ["agent-review-one", "workflow-external-one"], additionalForbiddenActions: ["Agent deploy forbidden"] }; }
function workflow() { return { id: "workflow-one", projectId: "project-one", departmentId: "department-one", version: 13, name: "Workflow one", summary: "Runs bounded approved work.", status: "active", triggerMode: "manual", goals: ["Produce reviewed output"], nonGoals: ["Deploy automatically"], steps: [{ id: "execute-one", kind: "agent_task", name: "Execute approved task", dependsOnStepIds: ["approve-one"], agentId: "agent-one", agentBindingId: "agent-binding-one", outputType: "patch", requestedResources: [{ resourceId: "repository-one", capabilities: ["read_metadata", "propose_change"] }], modelProfileId: "model-shared", knowledgeCollectionIds: ["knowledge-one"], toolIds: ["tool-read"], maxAttempts: 2, timeoutMinutes: 30, actionMode: "external_action", requiredApprovalAction: "workflow-external-one" }, { id: "approve-one", kind: "approval_gate", name: "Owner approval", dependsOnStepIds: [], approvalAction: "workflow-external-one" }], finalStepIds: ["execute-one"], additionalRequiredApprovalActions: ["workflow-review-one"], additionalForbiddenActions: ["Workflow publish forbidden"] }; }
function creation() { const projectRegistry = registry(); return { runId: "run-one", requestId: "request-one", createdAt: "2026-08-24T10:15:30.000Z", schedulerInput: { registry: clone(projectRegistry), policy: { workspaceId: "workspace-primary", status: "active", maxConcurrentRuns: 8, maxQueuedRuns: 512, projectPolicies: [{ projectId: "project-one", status: "active", maxQueuedRuns: 256, allowedPriorities: ["P0", "P1", "P2", "P3", "P4"] }] }, queuedRequests: [{ id: "request-one", workspaceId: "workspace-primary", projectId: "project-one", bindingId: "workflow-binding-one", modelProfileId: "model-shared", idempotencyKey: "idempotency-one", priority: "P2", sequence: 1 }], runningRuns: [], lastDispatchedProjectId: null }, workflowCatalog: { registry: projectRegistry, agents: [{ bindingId: "agent-binding-one", agentManifest: agent() }], workflows: [{ bindingId: "workflow-binding-one", workflowManifest: workflow() }] } }; }
function apply(snapshot: any, kind: string, index: number, extra: Record<string, unknown> = {}) { const decision = evaluateWorkflowRunTransition({ snapshot, event: { eventId: `event-${index}`, runId: snapshot.runId, kind, sequence: snapshot.revision + 1, occurredAt: `2026-08-24T10:15:${30 + index}.000Z`, actorKind: "owner", actorId: "owner-one", ...extra } }); assert.equal(decision.verdict, "allow", JSON.stringify(decision.reasons)); assert.ok(decision.nextSnapshot); return decision.nextSnapshot; }
function factualRequest() { const created = createWorkflowRunSnapshot(creation()); assert.equal(created.verdict, "allow", JSON.stringify(created.reasons)); assert.ok(created.snapshot); let snapshot = apply(created.snapshot, "run_started", 1); snapshot = apply(snapshot, "approval_requested", 2, { stepId: "approve-one", approvalRequestId: "approval-one" }); snapshot = apply(snapshot, "approval_granted", 3, { stepId: "approve-one", approvalRequestId: "approval-one" }); snapshot = apply(snapshot, "step_started", 4, { stepId: "execute-one" }); const admission = evaluateModelInvocationAdmission({ snapshot, draft: { invocationId: "invocation-one", invocationSequence: 1, stepId: "execute-one", messages: [{ role: "system", content: "Follow bounded instructions.", toolCallId: null }, { role: "user", content: "Prepare the proposal.", toolCallId: null }], contextArtifactIds: ["artifact-one"] }, existingRequests: [] }); assert.equal(admission.verdict, "allow", JSON.stringify(admission.reasons)); assert.ok(admission.normalizedRequest); return clone(admission.normalizedRequest); }
function identity(overrides: Record<string, unknown> = {}) { return { providerId: "provider-mock", providerKind: "mock", deploymentId: "deployment-mock", providerModelId: "mock/model:alias", providerRequestModelId: "mock/model:v1", providerModelVersion: "version-1", ...overrides }; }
function health(status = "healthy", overrides: Record<string, unknown> = {}) { return { providerId: "provider-mock", deploymentId: "deployment-mock", status, observedAt: "2026-08-24T10:15:30.000Z", latencyMs: 5, detailCode: null, ...overrides }; }
function result(request = factualRequest(), overrides: Record<string, unknown> = {}) { return { invocationId: request.invocationId, outcome: "succeeded", finishReason: "stop", providerId: "provider-mock", providerModelId: "mock/model:alias", providerRequestModelId: "mock/model:v1", providerModelVersion: "version-1", outputText: "Deterministic mock output.", structuredOutput: null, toolCallProposals: [], usage: { inputTokens: 10, outputTokens: 5, totalTokens: 15 }, latencyMs: 5, costUsdMicros: 0, error: null, ...overrides }; }
function config(scripts: unknown[] = [{ request: factualRequest(), result: result() }], overrides: Record<string, unknown> = {}) { return { identity: identity(), health: health(), scripts, ...overrides }; }
function codes(decision: { reasons: readonly { code: string }[] }) { return decision.reasons.map((reason) => reason.code); }
function deeplyFrozen(value: unknown): boolean { if (typeof value !== "object" || value === null) return true; return Object.isFrozen(value) && Object.values(value).every(deeplyFrozen); }

test("factory builds a provider from a real AI-021/AI-022 factual request", () => { const request = factualRequest(); assert.equal(request.runId, "run-one"); assert.equal(request.stepId, "execute-one"); assert.deepEqual(request.toolIds, ["tool-read"]); const input = config([{ request, result: result(request) }]); const before = clone(input); const decision = createDeterministicMockModelProvider(input); assert.equal(decision.verdict, "allow", JSON.stringify(decision.reasons)); assert.ok(decision.provider); assert.ok(decision.normalizedConfig); assert.equal(decision.provider.identity.providerKind, "mock"); assert.equal(deeplyFrozen(decision.normalizedConfig), true); assert.deepEqual(input, before); });
test("valid success script returns deterministic fresh deeply frozen results", async () => { const request = factualRequest(); const factory = createDeterministicMockModelProvider(config([{ request, result: result(request) }])); assert.ok(factory.provider); const first = await factory.provider.run(request); const second = await factory.provider.run(request); assert.equal(first.verdict, "allow", JSON.stringify(first.reasons)); assert.deepEqual(first, second); assert.notEqual(first, second); assert.notEqual(first.normalizedResult, second.normalizedResult); assert.equal(deeplyFrozen(first), true); });
test("valid failed provider error script is returned as factual normalized result", async () => { const request = factualRequest(); const failed = result(request, { outcome: "failed", finishReason: "error", outputText: null, error: { category: "provider_error", code: "mock-failure", message: "Deterministic failure.", retryable: false } }); const factory = createDeterministicMockModelProvider(config([{ request, result: failed }])); assert.ok(factory.provider); const decision = await factory.provider.run(request); assert.equal(decision.verdict, "allow"); assert.equal(decision.normalizedResult?.outcome, "failed"); });
test("canonical content-filtered failure is supported", async () => { const request = factualRequest(); const filtered = result(request, { outcome: "failed", finishReason: "content_filter", outputText: null, error: { category: "content_filtered", code: "mock-filter", message: "Filtered deterministically.", retryable: false } }); const factory = createDeterministicMockModelProvider(config([{ request, result: filtered }])); assert.ok(factory.provider); assert.equal((await factory.provider.run(request)).normalizedResult?.finishReason, "content_filter"); });
test("structured-output-only success is supported", async () => { const request = factualRequest(); const structured = result(request, { outputText: null, structuredOutput: { status: "ready", items: [1, true] } }); const factory = createDeterministicMockModelProvider(config([{ request, result: structured }])); assert.ok(factory.provider); const decision = await factory.provider.run(request); assert.equal(decision.verdict, "allow"); assert.deepEqual(decision.normalizedResult?.structuredOutput, { items: [1, true], status: "ready" }); });
test("allowed tool proposal is returned but never executed", async () => { const request = factualRequest(); const proposal = result(request, { finishReason: "tool_calls", outputText: null, toolCallProposals: [{ toolCallId: "call-one", toolId: "tool-read", arguments: { path: "src" } }] }); const factory = createDeterministicMockModelProvider(config([{ request, result: proposal }])); assert.ok(factory.provider); const decision = await factory.provider.run(request); assert.equal(decision.verdict, "allow"); assert.equal(decision.normalizedResult?.toolCallProposals[0]?.toolId, "tool-read"); });

test("factory denies a proposal for an unknown tool with raw script path", () => { const request = factualRequest(); const proposal = result(request, { finishReason: "tool_calls", outputText: null, toolCallProposals: [{ toolCallId: "call-one", toolId: "tool-write", arguments: {} }] }); const decision = createDeterministicMockModelProvider(config([{ request, result: proposal }])); assert.equal(decision.verdict, "deny"); assert.deepEqual(codes(decision), ["tool_not_allowed"]); assert.equal(decision.reasons[0]?.path, "scripts[0].result.toolCallProposals[0].toolId"); assert.equal(decision.provider, null); assert.equal(decision.normalizedConfig, null); });
test("factory denies request/result invocation mismatch", () => { const request = factualRequest(); const decision = createDeterministicMockModelProvider(config([{ request, result: result(request, { invocationId: "invocation-other" }) }])); assert.deepEqual(codes(decision), ["invocation_id_mismatch"]); assert.equal(decision.reasons[0]?.path, "scripts[0].result.invocationId"); });
test("factory denies provider and model identity mismatches", () => { for (const [field, value, code] of [["providerId", "provider-other", "provider_id_mismatch"], ["providerModelId", "other/model", "provider_model_id_mismatch"], ["providerRequestModelId", "other/request-model", "provider_request_model_id_mismatch"], ["providerModelVersion", "version-other", "provider_model_version_mismatch"]] as const) { const request = factualRequest(); const decision = createDeterministicMockModelProvider(config([{ request, result: result(request, { [field]: value }) }])); assert.deepEqual(codes(decision), [code]); assert.equal(decision.reasons[0]?.path, `scripts[0].result.${field}`); assert.equal(decision.provider, null); } });
test("factory denies duplicate scripted invocation IDs with source path", () => { const request = factualRequest(); const duplicate = clone(request); const decision = createDeterministicMockModelProvider(config([{ request, result: result(request) }, { request: duplicate, result: result(duplicate) }])); assert.deepEqual(codes(decision), ["duplicate_invocation_id"]); assert.equal(decision.reasons[0]?.path, "scripts[1].request.invocationId"); });

test("run denies unknown invocation ID without fallback", async () => { const request = factualRequest(); const factory = createDeterministicMockModelProvider(config([{ request, result: result(request) }])); assert.ok(factory.provider); const unknown = { ...clone(request), invocationId: "invocation-unknown" }; const decision = await factory.provider.run(unknown); assert.deepEqual(codes(decision), ["script_not_found"]); assert.equal(decision.reasons[0]?.path, "$.invocationId"); assert.equal(decision.normalizedResult, null); });
test("run denies same invocation ID with changed request as conflicting replay", async () => { const request = factualRequest(); const factory = createDeterministicMockModelProvider(config([{ request, result: result(request) }])); assert.ok(factory.provider); const changed = { ...clone(request), messages: [{ role: "user", content: "changed", toolCallId: null }] }; const decision = await factory.provider.run(changed); assert.deepEqual(codes(decision), ["conflicting_replay"]); assert.equal(decision.requestDecision?.verdict, "allow"); assert.equal(decision.normalizedResult, null); });
test("run preserves factual AI-022 request denial", async () => { const factory = createDeterministicMockModelProvider(config()); assert.ok(factory.provider); const hostile = Object.defineProperty({}, "invocationId", { enumerable: true, get() { throw new Error("no read"); } }); const decision = await factory.provider.run(hostile); assert.equal(decision.verdict, "deny"); assert.equal(decision.requestDecision?.verdict, "deny"); assert.equal(decision.resultDecision, null); assert.equal(decision.normalizedResult, null); });

test("factory preserves factual invalid scripted request and source path", () => { const decision = createDeterministicMockModelProvider(config([{ request: {}, result: result() }])); assert.deepEqual(codes(decision), ["invalid_script_request"]); assert.equal(decision.reasons[0]?.path, "scripts[0].request"); assert.equal(decision.provider, null); });
test("factory preserves factual invalid scripted result and source path", () => { const request = factualRequest(); const decision = createDeterministicMockModelProvider(config([{ request, result: {} }])); assert.deepEqual(codes(decision), ["invalid_script_result"]); assert.equal(decision.reasons[0]?.path, "scripts[0].result"); assert.equal(decision.provider, null); });
test("factory rejects getters, proxies, cycles, functions, and non-data config", () => { const getter = config(); Object.defineProperty(getter, "identity", { enumerable: true, get() { throw new Error("no read"); } }); const proxy = new Proxy({}, { ownKeys() { throw new Error("trap"); } }); const cycle: any = config(); cycle.self = cycle; for (const value of [getter, proxy, cycle, { ...config(), run: () => null }, new Set(), new Map(), new Date(), /x/u]) { assert.doesNotThrow(() => createDeterministicMockModelProvider(value)); const decision = createDeterministicMockModelProvider(value); assert.equal(decision.verdict, "deny"); assert.equal(decision.provider, null); assert.equal(decision.normalizedConfig, null); } });
test("factory rejects sensitive config fields", () => { for (const field of ["apiKey", "credentials", "endpoint", "connectionId", "environmentVariableName", "secretRef"]) { const decision = createDeterministicMockModelProvider({ ...config(), [field]: "not-allowed" }); assert.equal(decision.verdict, "deny"); assert.equal(decision.reasons[0]?.path, "$" ); assert.equal(decision.provider, null); } });
test("factory enforces bounded non-empty ordinary scripts", () => { assert.ok(codes(createDeterministicMockModelProvider(config([]))).includes("invalid_scripts")); assert.ok(codes(createDeterministicMockModelProvider(config(Array.from({ length: mockModelProviderLimits.maxScripts + 1 }, () => ({}))))).includes("limit_exceeded")); const sparse = Array(2); sparse[0] = { request: factualRequest(), result: result() }; assert.equal(createDeterministicMockModelProvider(config(sparse)).verdict, "deny"); });

test("health returns configured healthy, degraded, and unavailable factual states", async () => { for (const status of ["healthy", "degraded", "unavailable"]) { const factory = createDeterministicMockModelProvider(config(undefined, { health: health(status) })); assert.ok(factory.provider); const first = await factory.provider.health(); const second = await factory.provider.health(); assert.equal(first.verdict, "allow"); assert.equal(first.normalizedHealth?.status, status); assert.deepEqual(first, second); assert.notEqual(first, second); assert.notEqual(first.normalizedHealth, second.normalizedHealth); assert.equal(deeplyFrozen(first), true); } });
test("factory requires mock identity and exact health identity", () => { assert.deepEqual(codes(createDeterministicMockModelProvider(config(undefined, { identity: identity({ providerKind: "local" }) }))), ["identity_not_mock"]); for (const [field, value] of [["providerId", "provider-other"], ["deploymentId", "deployment-other"]] as const) { const decision = createDeterministicMockModelProvider(config(undefined, { health: health("healthy", { [field]: value }) })); assert.deepEqual(codes(decision), ["health_identity_mismatch"]); assert.equal(decision.reasons[0]?.path, `health.${field}`); } });
test("reverse script order normalizes canonically and does not change factual runs", async () => { const one = factualRequest(); const two = { ...clone(one), invocationId: "invocation-two", invocationSequence: 2 }; const scripts = [{ request: two, result: result(two) }, { request: one, result: result(one) }]; const forward = createDeterministicMockModelProvider(config(scripts)); const reverse = createDeterministicMockModelProvider(config([...scripts].reverse())); assert.equal(forward.verdict, "allow"); assert.deepEqual(reverse.normalizedConfig, forward.normalizedConfig); assert.deepEqual(reverse.reasons, forward.reasons); assert.ok(forward.provider && reverse.provider); assert.deepEqual(await reverse.provider.run(one), await forward.provider.run(one)); });
test("reason count is capped", () => { const scripts = Array.from({ length: mockModelProviderLimits.maxScripts }, (_, index) => ({ request: { invalid: index }, result: { invalid: index } })); const decision = createDeterministicMockModelProvider(config(scripts)); assert.ok(decision.reasons.length <= modelProviderAdapterLimits.maxReasons); assert.equal(decision.provider, null); });
test("factory and provider retain no caller references", async () => { const request = factualRequest(); const input = config([{ request, result: result(request) }]); const before = clone(input); const factory = createDeterministicMockModelProvider(input); assert.ok(factory.provider && factory.normalizedConfig); assert.deepEqual(input, before); assert.notEqual(factory.normalizedConfig, input); const runInput = clone(request); const runBefore = clone(runInput); await factory.provider.run(runInput); assert.deepEqual(runInput, runBefore); });
test("production source contains no runtime side effects, SDKs, routing, or tool execution", () => { const source = readFileSync(new URL("../lib/providers/deterministic-mock-model-provider.ts", import.meta.url), "utf8"); for (const token of ["JSON" + ".stringify", "locale" + "Compare", "Date" + ".now", "Math" + ".random", "set" + "Timeout", "set" + "Interval", "fet" + "ch(", "process" + ".env", "node:" + "fs", "child_" + "process", "Open" + "AI", "Anth" + "ropic", "Deep" + "Seek", "Q" + "wen", ".execute(", "resolveModelInvocationRoute"]) assert.equal(source.includes(token), false, token); assert.ok(modelInvocationLimits.maxLatencyMs > 0); });
