import assert from "node:assert/strict";
import test from "node:test";

/* eslint-disable @typescript-eslint/no-explicit-any -- hostile fixture mutations intentionally cross unknown contract boundaries */

const contract = (await import(new URL("../lib/contracts/model-provider-registry.ts", import.meta.url).href)) as typeof import("../lib/contracts/model-provider-registry");
const runContract = (await import(new URL("../lib/contracts/workflow-run.ts", import.meta.url).href)) as typeof import("../lib/contracts/workflow-run");
const invocationContract = (await import(new URL("../lib/contracts/model-invocation.ts", import.meta.url).href)) as typeof import("../lib/contracts/model-invocation");

const {
  evaluateWorkspaceModelProviderRegistry, isModelDataHandlingRequirement, isModelDeploymentMode,
  isModelLatencyClass, isModelProviderCapability, isModelProviderKind, isModelProviderStatus,
  isModelQualityTier, isModelRoutingVerdict, modelDataHandlingRequirements, modelDeploymentModes,
  modelLatencyClasses, modelProviderCapabilities, modelProviderKinds, modelProviderRegistryLimits,
  modelProviderStatuses, modelQualityTiers, modelRoutingVerdicts, parseModelDataHandlingRequirement,
  parseModelDeploymentMode, parseModelLatencyClass, parseModelProviderCapability, parseModelProviderKind,
  parseModelProviderStatus, parseModelQualityTier, parseModelRoutingVerdict, resolveModelInvocationRoute,
  validateAndNormalizeModelProviderRegistry,
} = contract;
const { createWorkflowRunSnapshot, evaluateWorkflowRunTransition } = runContract;
const { evaluateModelInvocationAdmission } = invocationContract;

function clone<T>(value: T): T { return structuredClone(value); }
function budget() { return { maxConcurrentRuns: 4, maxAttemptsPerRun: 3, maxRunMinutes: 120, dailyTokenBudget: 1_000_000, monthlyCostBudgetUsdCents: 250_000 }; }
function project(egress = "forbidden", dataRegion = "eu") { return { id: "project-one", workspaceId: "workspace-primary", version: 3, name: "Project one", slug: "project-one", summary: "Owner-controlled project context.", kind: "internal_product", status: "active", defaultLocale: "en-US", timeZone: "UTC", dataRegion, dataClassification: "confidential", goals: ["Operate safely"], nonGoals: ["Autonomous actions"], tags: ["one"], resources: [{ id: "repository-one", kind: "code_repository", label: "Repository one", status: "connected", connectionId: "connection-one", resourceRef: "owner/repository-one", capabilities: ["read_metadata", "propose_change"] }], allowedModelProfileIds: ["model-shared", "model-one"], knowledgeCollectionIds: ["knowledge-one"], policy: { externalActionMode: "approval_required", dataEgressMode: egress, requiredApprovalActions: ["project-review-one"], forbiddenActions: ["Project action forbidden"] }, budget: budget() }; }
function department(egress = "forbidden") { return { id: "department-one", projectId: "project-one", version: 5, code: "development", name: "Department one", summary: "Reviewed work.", status: "active", operatingMode: "approval_gated", goals: ["Build reviewed artifacts"], nonGoals: ["Deploy automatically"], resourceGrants: [{ resourceId: "repository-one", capabilities: ["read_metadata", "propose_change"] }], allowedModelProfileIds: ["model-shared", "model-one"], knowledgeCollectionIds: ["knowledge-one"], enabledWorkflowIds: ["workflow-one"], operatorRoleIds: ["role-owner"], modelRouting: { primaryModelProfileId: "model-shared", fallbackModelProfileIds: ["model-one"], reviewerModelProfileId: "model-one", independentReviewRequired: true }, policy: { externalActionMode: "approval_required", dataEgressMode: egress, additionalRequiredApprovalActions: ["department-review-one"], additionalForbiddenActions: ["Department publish forbidden"] }, budget: { ...budget(), maxConcurrentRuns: 3, maxAttemptsPerRun: 2, maxRunMinutes: 60 } }; }
function binding(kind: "agent" | "workflow", egress = "forbidden") { return { id: `${kind}-binding-one`, projectId: "project-one", departmentId: "department-one", version: kind === "agent" ? 7 : 8, status: "active", kind, subjectId: `${kind}-one`, requestedResources: [{ resourceId: "repository-one", capabilities: ["read_metadata", "propose_change"] }], requestedModelProfileIds: ["model-shared", "model-one"], requestedKnowledgeCollectionIds: ["knowledge-one"], requestedBudget: { ...budget(), maxConcurrentRuns: 1, maxAttemptsPerRun: 2, maxRunMinutes: 30 }, externalActionMode: "approval_required", dataEgressMode: egress, additionalRequiredApprovalActions: [kind === "workflow" ? "workflow-external-one" : "agent-review-one"], additionalForbiddenActions: [`${kind} deploy forbidden`] }; }
function projectRegistry(egress = "forbidden", dataRegion = "eu") { return { workspaceId: "workspace-primary", projects: [{ projectManifest: project(egress, dataRegion), departmentManifests: [department(egress)], bindings: [binding("agent", egress), binding("workflow", egress)] }] }; }
function agent() { return { id: "agent-one", projectId: "project-one", departmentId: "department-one", version: 11, roleCode: "developer", name: "Developer one", summary: "Creates bounded artifacts.", status: "active", instructionProfileId: "instructions-one", goals: ["Create reviewed artifacts"], nonGoals: ["Deploy automatically"], outputTypes: ["patch", "test_report"], allowedWorkflowIds: ["workflow-one"], allowedToolIds: ["tool-read"], allowedModelProfileIds: ["model-shared", "model-one"], knowledgeCollectionIds: ["knowledge-one"], modelRouting: { primaryModelProfileId: "model-shared", fallbackModelProfileIds: ["model-one"], reviewerModelProfileId: "model-one", independentReviewRequired: true }, additionalRequiredApprovalActions: ["agent-review-one", "workflow-external-one"], additionalForbiddenActions: ["Agent deploy forbidden"] }; }
function workflow(toolIds: string[] = ["tool-read"]) { return { id: "workflow-one", projectId: "project-one", departmentId: "department-one", version: 13, name: "Workflow one", summary: "Runs bounded approved work.", status: "active", triggerMode: "manual", goals: ["Produce reviewed output"], nonGoals: ["Deploy automatically"], steps: [{ id: "execute-one", kind: "agent_task", name: "Execute approved task", dependsOnStepIds: ["approve-one"], agentId: "agent-one", agentBindingId: "agent-binding-one", outputType: "patch", requestedResources: [{ resourceId: "repository-one", capabilities: ["read_metadata", "propose_change"] }], modelProfileId: "model-shared", knowledgeCollectionIds: ["knowledge-one"], toolIds, maxAttempts: 2, timeoutMinutes: 30, actionMode: "external_action", requiredApprovalAction: "workflow-external-one" }, { id: "approve-one", kind: "approval_gate", name: "Owner approval", dependsOnStepIds: [], approvalAction: "workflow-external-one" }], finalStepIds: ["execute-one"], additionalRequiredApprovalActions: ["workflow-review-one"], additionalForbiddenActions: ["Workflow publish forbidden"] }; }
function creation(egress = "forbidden", dataRegion = "eu", toolIds: string[] = ["tool-read"]) { const registry = projectRegistry(egress, dataRegion); return { runId: "run-one", requestId: "request-one", createdAt: "2026-08-23T10:15:30.000Z", schedulerInput: { registry: clone(registry), policy: { workspaceId: "workspace-primary", status: "active", maxConcurrentRuns: 8, maxQueuedRuns: 512, projectPolicies: [{ projectId: "project-one", status: "active", maxQueuedRuns: 256, allowedPriorities: ["P0", "P1", "P2", "P3", "P4"] }] }, queuedRequests: [{ id: "request-one", workspaceId: "workspace-primary", projectId: "project-one", bindingId: "workflow-binding-one", modelProfileId: "model-shared", idempotencyKey: "idempotency-one", priority: "P2", sequence: 1 }], runningRuns: [], lastDispatchedProjectId: null }, workflowCatalog: { registry, agents: [{ bindingId: "agent-binding-one", agentManifest: agent() }], workflows: [{ bindingId: "workflow-binding-one", workflowManifest: workflow(toolIds) }] } }; }
function apply(snapshot: any, kind: string, index: number, extra: Record<string, unknown> = {}) { const decision = evaluateWorkflowRunTransition({ snapshot, event: { eventId: `event-${index}`, runId: snapshot.runId, kind, sequence: snapshot.revision + 1, occurredAt: `2026-08-23T10:15:${30 + index}.000Z`, actorKind: "owner", actorId: "owner-one", ...extra } }); assert.equal(decision.verdict, "allow", JSON.stringify(decision.reasons)); assert.ok(decision.nextSnapshot); return decision.nextSnapshot; }
function runningSnapshot(egress = "forbidden", dataRegion = "eu", toolIds: string[] = ["tool-read"]) { const created = createWorkflowRunSnapshot(creation(egress, dataRegion, toolIds)); assert.equal(created.verdict, "allow", JSON.stringify(created.reasons)); assert.ok(created.snapshot); let value = apply(created.snapshot, "run_started", 1); value = apply(value, "approval_requested", 2, { stepId: "approve-one", approvalRequestId: "approval-one" }); value = apply(value, "approval_granted", 3, { stepId: "approve-one", approvalRequestId: "approval-one" }); return apply(value, "step_started", 4, { stepId: "execute-one" }); }
function draft(overrides: Record<string, unknown> = {}) { return { invocationId: "invocation-one", invocationSequence: 1, stepId: "execute-one", messages: [{ role: "system", content: "Follow bounded instructions.", toolCallId: null }, { role: "user", content: "Prepare patch proposal.", toolCallId: null }], contextArtifactIds: ["artifact-one"], ...overrides }; }
function provider(id = "provider-local", mode = "local", egress: string[] = ["forbidden", "redacted_only", "approved_minimum"], overrides: Record<string, unknown> = {}) { return { id, kind: mode === "local" ? "local" : "openai", status: "active", deploymentMode: mode, supportedDataRegions: ["eu"], supportedDataEgressModes: egress, capabilities: ["messages", "tool_calls", "structured_output"], ...overrides }; }
function deployment(id = "deployment-local", providerId = "provider-local", overrides: Record<string, unknown> = {}) { return { id, providerId, status: "active", providerModelId: "model/audit:v1", providerModelVersion: "2026-08-23", capabilities: ["messages", "tool_calls", "structured_output"], supportedOutputTypes: ["patch", "test_report"], maxInputTokens: 128_000, maxOutputTokens: 16_000, inputCostUsdMicrosPerMillionTokens: 1_000_000, outputCostUsdMicrosPerMillionTokens: 2_000_000, latencyClass: "standard", qualityTier: "reasoning", ...overrides }; }
function profile(modelProfileId = "model-shared", candidates: unknown[] = [{ deploymentId: "deployment-local", priority: 1 }], overrides: Record<string, unknown> = {}) { return { modelProfileId, status: "active", requiredCapabilities: ["messages", "tool_calls"], supportedOutputTypes: ["patch", "test_report"], candidates, ...overrides }; }
function providerRegistry(overrides: Record<string, unknown> = {}) { return { workspaceId: "workspace-primary", version: 1, providers: [provider()], deployments: [deployment()], modelProfiles: [profile(), profile("model-one")], ...overrides }; }
function routeInput(egress = "forbidden", registry: unknown = providerRegistry(), existingRequests: unknown[] = [], dataRegion = "eu", toolIds: string[] = ["tool-read"]) { return { projectRegistry: projectRegistry(egress, dataRegion), modelProviderRegistry: registry, invocationAdmission: { snapshot: runningSnapshot(egress, dataRegion, toolIds), draft: draft(), existingRequests } }; }
function codes(decision: { reasons: readonly { code: string }[] }) { return decision.reasons.map((item) => item.code); }
function deeplyFrozen(value: unknown): boolean { if (typeof value !== "object" || value === null) return true; if (!Object.isFrozen(value)) return false; return Object.values(value).every(deeplyFrozen); }
function renameOneToTwo<T>(value: T): T { const output = clone(value) as any; const visit = (entry: any): void => { if (Array.isArray(entry)) { for (const [index, item] of entry.entries()) entry[index] = typeof item === "string" ? item.replaceAll("one", "two") : item; for (const item of entry) if (typeof item === "object" && item !== null) visit(item); return; } for (const [key, item] of Object.entries(entry)) { if (typeof item === "string") entry[key] = item.replaceAll("one", "two"); else if (typeof item === "object" && item !== null) visit(item); } }; visit(output); return output; }
function twoProjectRegistry(reverse = false) { const first = projectRegistry().projects[0]; const second = renameOneToTwo(first); return { workspaceId: "workspace-primary", projects: reverse ? [second, first] : [first, second] }; }

test("exports exact frozen canonical enums, guards, parsers, and bounded limits", () => {
  assert.deepEqual(modelProviderKinds, ["openai", "anthropic", "deepseek", "qwen", "local", "mock"]); assert.deepEqual(modelProviderStatuses, ["active", "paused", "disabled"]); assert.deepEqual(modelDeploymentModes, ["remote", "local"]); assert.deepEqual(modelProviderCapabilities, ["messages", "structured_output", "tool_calls", "vision", "long_context"]); assert.deepEqual(modelRoutingVerdicts, ["allow", "deny"]); assert.deepEqual(modelDataHandlingRequirements, ["local_only", "redaction_required", "approval_required"]); assert.deepEqual(modelLatencyClasses, ["realtime", "standard", "batch"]); assert.deepEqual(modelQualityTiers, ["economy", "balanced", "reasoning"]);
  for (const value of [modelProviderKinds, modelProviderStatuses, modelDeploymentModes, modelProviderCapabilities, modelRoutingVerdicts, modelDataHandlingRequirements, modelLatencyClasses, modelQualityTiers, modelProviderRegistryLimits]) assert.equal(Object.isFrozen(value), true);
  for (const [values, guard, parser] of [[modelProviderKinds, isModelProviderKind, parseModelProviderKind], [modelProviderStatuses, isModelProviderStatus, parseModelProviderStatus], [modelDeploymentModes, isModelDeploymentMode, parseModelDeploymentMode], [modelProviderCapabilities, isModelProviderCapability, parseModelProviderCapability], [modelRoutingVerdicts, isModelRoutingVerdict, parseModelRoutingVerdict], [modelDataHandlingRequirements, isModelDataHandlingRequirement, parseModelDataHandlingRequirement], [modelLatencyClasses, isModelLatencyClass, parseModelLatencyClass], [modelQualityTiers, isModelQualityTier, parseModelQualityTier]] as const) { for (const value of values) { assert.equal(guard(value as never), true); assert.equal(parser(value as never), value); } assert.equal(guard("invalid" as never), false); assert.equal(parser("invalid" as never), null); }
});

test("normalizes exact schemas canonically, freshly, and deeply frozen", () => { const input = providerRegistry(); const decision = validateAndNormalizeModelProviderRegistry(input); assert.equal(decision.verdict, "allow", JSON.stringify(decision.reasons)); assert.ok(decision.normalizedRegistry); assert.notEqual(decision.normalizedRegistry, input); assert.equal(deeplyFrozen(decision), true); assert.deepEqual(input, providerRegistry()); });
test("unknown or sensitive provider fields deny without partial registry", () => { for (const field of ["apiKey", "endpointUrl", "environmentVariableName", "connectionId"]) { const input = providerRegistry() as any; input.providers[0][field] = "secret-or-config"; const decision = validateAndNormalizeModelProviderRegistry(input); assert.equal(decision.verdict, "deny"); assert.equal(decision.normalizedRegistry, null); } });
test("remote provider cannot claim forbidden egress", () => { const input = providerRegistry({ providers: [provider("provider-remote", "remote")], deployments: [deployment("deployment-remote", "provider-remote")], modelProfiles: [profile("model-shared", [{ deploymentId: "deployment-remote", priority: 1 }]), profile("model-one", [{ deploymentId: "deployment-remote", priority: 1 }])] }); assert.equal(validateAndNormalizeModelProviderRegistry(input).verdict, "deny"); });
test("provider kinds enforce canonical deployment modes with exact source paths", () => { for (const kind of ["openai", "anthropic", "deepseek", "qwen", "local"] as const) { const validMode = kind === "local" ? "local" : "remote"; const invalidMode = validMode === "local" ? "remote" : "local"; const valid = providerRegistry() as any; valid.providers[0].kind = kind; valid.providers[0].deploymentMode = validMode; valid.providers[0].supportedDataEgressModes = validMode === "remote" ? ["redacted_only"] : ["forbidden"]; assert.equal(validateAndNormalizeModelProviderRegistry(valid).verdict, "allow", kind); const invalid = clone(valid); invalid.providers[0].deploymentMode = invalidMode; invalid.providers[0].supportedDataEgressModes = invalidMode === "remote" ? ["redacted_only"] : ["forbidden"]; const first = validateAndNormalizeModelProviderRegistry(invalid); const repeated = validateAndNormalizeModelProviderRegistry(invalid); assert.equal(first.verdict, "deny", kind); assert.equal(first.normalizedRegistry, null); assert.deepEqual(first, repeated); assert.ok(first.reasons.some((item) => item.code === "provider_deployment_mode_mismatch" && item.path === "providers[0].deploymentMode")); } for (const mode of ["local", "remote"] as const) { const mock = providerRegistry() as any; mock.providers[0].kind = "mock"; mock.providers[0].deploymentMode = mode; mock.providers[0].supportedDataEgressModes = mode === "remote" ? ["redacted_only"] : ["forbidden"]; assert.equal(validateAndNormalizeModelProviderRegistry(mock).verdict, "allow"); } });
test("valid mixed provider deployment modes normalize independently of caller order", () => { const kinds = ["openai", "anthropic", "deepseek", "qwen", "local", "mock"] as const; const input = providerRegistry() as any; input.providers = kinds.map((kind, index) => { const mode = kind === "local" || kind === "mock" ? "local" : "remote"; return provider(`provider-${index}`, mode, mode === "remote" ? ["redacted_only"] : ["forbidden"], { kind }); }); input.deployments = kinds.map((_, index) => deployment(`deployment-${index}`, `provider-${index}`)); input.modelProfiles = [profile("model-shared", [{ deploymentId: "deployment-0", priority: 1 }]), profile("model-one", [{ deploymentId: "deployment-0", priority: 1 }])]; const reversed = clone(input); reversed.providers.reverse(); reversed.deployments.reverse(); const forward = validateAndNormalizeModelProviderRegistry(input); const reverse = validateAndNormalizeModelProviderRegistry(reversed); assert.equal(forward.verdict, "allow", JSON.stringify(forward.reasons)); assert.deepEqual(reverse, forward); assert.notEqual(reverse.normalizedRegistry, forward.normalizedRegistry); assert.equal(deeplyFrozen(forward), true); });
test("duplicate IDs and missing references deny with source-accurate paths", () => { const duplicated = providerRegistry() as any; duplicated.providers.push(clone(duplicated.providers[0])); assert.ok(validateAndNormalizeModelProviderRegistry(duplicated).reasons.some((item) => item.code === "duplicate_provider_id" && item.path === "providers[1].id")); const missing = providerRegistry() as any; missing.modelProfiles[0].candidates[0].deploymentId = "deployment-missing"; assert.ok(validateAndNormalizeModelProviderRegistry(missing).reasons.some((item) => item.code === "deployment_not_found" && item.path === "modelProfiles[0].candidates[0].deploymentId")); });
test("candidate priority, uniqueness, capability, and output compatibility are fail-closed", () => { for (const mutate of [(input: any) => { input.modelProfiles[0].candidates[0].priority = 2; }, (input: any) => { input.modelProfiles[0].requiredCapabilities.push("vision"); }, (input: any) => { input.modelProfiles[0].supportedOutputTypes.push("summary"); }]) { const input = providerRegistry(); mutate(input); const decision = validateAndNormalizeModelProviderRegistry(input); assert.equal(decision.verdict, "deny"); assert.equal(decision.normalizedRegistry, null); } });
test("empty capability requirements are valid while unsafe audit identifiers deny", () => { const empty = providerRegistry() as any; empty.providers[0].capabilities = []; empty.deployments[0].capabilities = []; for (const route of empty.modelProfiles) route.requiredCapabilities = []; assert.equal(validateAndNormalizeModelProviderRegistry(empty).verdict, "allow"); const unsafe = providerRegistry() as any; unsafe.deployments[0].providerModelId = "model id with spaces"; assert.equal(validateAndNormalizeModelProviderRegistry(unsafe).verdict, "deny"); });
test("data regions use canonical AI-013 strings, trim, deduplicate, sort, and preserve error paths", () => { const input = providerRegistry() as any; input.providers[0].supportedDataRegions = [" eu-west/primary ", "eu", "eu-west/primary"]; const decision = validateAndNormalizeModelProviderRegistry(input); assert.equal(decision.verdict, "allow", JSON.stringify(decision.reasons)); assert.deepEqual(decision.normalizedRegistry?.providers[0]?.supportedDataRegions, ["eu", "eu-west/primary"]); assert.deepEqual(input.providers[0].supportedDataRegions, [" eu-west/primary ", "eu", "eu-west/primary"]); for (const [value, code] of [["bad\nregion", "invalid_provider_registry"], ["bad\rregion", "invalid_provider_registry"], ["bad\u2028region", "invalid_provider_registry"], ["bad\u2029region", "invalid_provider_registry"], ["\u2028eu", "invalid_provider_registry"], ["eu\u2029", "invalid_provider_registry"], ["x".repeat(65), "limit_exceeded"]] as const) { const invalid = providerRegistry() as any; invalid.providers[0].supportedDataRegions = ["eu", value]; const denied = validateAndNormalizeModelProviderRegistry(invalid); assert.ok(denied.reasons.some((item) => item.code === code && item.path === "providers[0].supportedDataRegions[1]")); assert.equal(denied.normalizedRegistry, null); } });
test("every collection boundary is bounded", () => { const cases: Array<[string, number]> = [["providers", modelProviderRegistryLimits.maxProviders], ["deployments", modelProviderRegistryLimits.maxDeployments], ["modelProfiles", modelProviderRegistryLimits.maxModelProfiles]]; for (const [field, maximum] of cases) { const input = providerRegistry() as any; input[field] = Array.from({ length: maximum + 1 }, () => ({})); assert.ok(codes(validateAndNormalizeModelProviderRegistry(input)).includes("limit_exceeded")); } const input = providerRegistry() as any; input.modelProfiles[0].candidates = Array.from({ length: modelProviderRegistryLimits.maxCandidatesPerProfile + 1 }, () => ({})); assert.ok(codes(validateAndNormalizeModelProviderRegistry(input)).includes("limit_exceeded")); });
test("hostile getters, proxies, cycles, Set, Map, sparse and derived arrays deny without throw", () => { const getter = {}; Object.defineProperty(getter, "workspaceId", { get() { throw new Error("no"); }, enumerable: true }); const proxy = new Proxy({}, { ownKeys() { throw new Error("no"); } }); const cycle: any = {}; cycle.self = cycle; const sparse = Array(2); const derived = Object.setPrototypeOf([], {}); for (const value of [getter, proxy, cycle, new Set(), new Map(), sparse, derived]) { assert.doesNotThrow(() => validateAndNormalizeModelProviderRegistry(value)); assert.equal(validateAndNormalizeModelProviderRegistry(value).verdict, "deny"); } });

test("workspace evaluation composes the real AI-016 decision and enforces profile completeness", () => { const allow = evaluateWorkspaceModelProviderRegistry({ projectRegistry: projectRegistry(), modelProviderRegistry: providerRegistry() }); assert.equal(allow.verdict, "allow", JSON.stringify(allow.reasons)); assert.equal(allow.projectRegistryDecision?.verdict, "allow"); const missing = providerRegistry({ modelProfiles: [profile()] }); const deny = evaluateWorkspaceModelProviderRegistry({ projectRegistry: projectRegistry(), modelProviderRegistry: missing }); assert.equal(deny.verdict, "deny"); assert.equal(deny.normalizedRegistry, null); assert.ok(codes(deny).includes("model_profile_missing")); });
test("Workspace completeness requires presence but permits paused and disabled unrelated profiles", () => { for (const status of ["paused", "disabled"]) { const registry = providerRegistry(); (registry.modelProfiles[1] as any).status = status; const input = { projectRegistry: projectRegistry(), modelProviderRegistry: registry }; const before = clone(input); const first = evaluateWorkspaceModelProviderRegistry(input); const second = evaluateWorkspaceModelProviderRegistry(input); assert.equal(first.verdict, "allow", JSON.stringify(first.reasons)); assert.deepEqual(second, first); assert.notEqual(second.normalizedRegistry, first.normalizedRegistry); assert.equal(deeplyFrozen(first), true); assert.deepEqual(input, before); const route = resolveModelInvocationRoute(routeInput("forbidden", registry)); assert.equal(route.verdict, "allow", JSON.stringify(route.reasons)); } });
test("paused profile used only by another Project does not block the exact active route", () => { const registry = providerRegistry({ modelProfiles: [profile("model-shared"), profile("model-one"), profile("model-two", [{ deploymentId: "deployment-local", priority: 1 }], { status: "paused" })] }); const forward = resolveModelInvocationRoute({ ...routeInput("forbidden", registry), projectRegistry: twoProjectRegistry() }); const reversedRegistry = clone(registry) as any; reversedRegistry.modelProfiles.reverse(); const reverse = resolveModelInvocationRoute({ ...routeInput("forbidden", reversedRegistry), projectRegistry: twoProjectRegistry(true) }); assert.equal(forward.verdict, "allow", JSON.stringify(forward.reasons)); assert.deepEqual(reverse, forward); assert.equal(forward.routePlan?.modelProfileId, "model-shared"); });
test("workspace mismatch and factual AI-016 deny preserve prerequisite decisions", () => { const mismatch = providerRegistry({ workspaceId: "workspace-other" }); const decision = evaluateWorkspaceModelProviderRegistry({ projectRegistry: projectRegistry(), modelProviderRegistry: mismatch }); assert.ok(codes(decision).includes("workspace_mismatch")); assert.equal(decision.projectRegistryDecision?.verdict, "allow"); const invalid = evaluateWorkspaceModelProviderRegistry({ projectRegistry: {}, modelProviderRegistry: providerRegistry() }); assert.deepEqual(codes(invalid), ["invalid_project_registry"]); assert.equal(invalid.projectRegistryDecision?.verdict, "deny"); });
test("reverse and repeated Workspace registry evaluation are deterministic and immutable", () => { const original = providerRegistry(); const reversed = clone(original) as any; reversed.providers.reverse(); reversed.deployments.reverse(); reversed.modelProfiles.reverse(); const forwardDecision = evaluateWorkspaceModelProviderRegistry({ projectRegistry: projectRegistry(), modelProviderRegistry: original }); const reverseDecision = evaluateWorkspaceModelProviderRegistry({ projectRegistry: projectRegistry(), modelProviderRegistry: reversed }); assert.deepEqual(reverseDecision, forwardDecision); assert.deepEqual(evaluateWorkspaceModelProviderRegistry({ projectRegistry: projectRegistry(), modelProviderRegistry: original }), forwardDecision); assert.deepEqual(original, providerRegistry()); });

test("local forbidden route allows only safe metadata and local_only handling", () => { const input = routeInput(); const before = clone(input); const decision = resolveModelInvocationRoute(input); assert.equal(decision.verdict, "allow", JSON.stringify(decision.reasons)); assert.equal(decision.projectRegistryDecision?.verdict, "allow"); assert.equal(decision.invocationAdmissionDecision?.verdict, "allow"); assert.ok(decision.routePlan); assert.equal(decision.routePlan.primary.dataHandlingRequirement, "local_only"); assert.equal(decision.routePlan.projectDataRegion, "eu"); assert.equal(decision.routePlan.dataEgressMode, "forbidden"); assert.equal(deeplyFrozen(decision), true); assert.deepEqual(input, before); const serialized = JSON.stringify(decision.routePlan); for (const forbidden of ["artifact-one", "resourceRef", "connectionId", "apiKey", "endpointUrl"]) assert.equal(serialized.includes(forbidden), false); });
test("slash dataRegion composes through real AI-016, validation, Workspace evaluation, and exact route", () => { const dataRegion = "eu-west/primary"; const registry = providerRegistry(); (registry.providers[0] as any).supportedDataRegions = [dataRegion]; const validation = validateAndNormalizeModelProviderRegistry(registry); assert.equal(validation.verdict, "allow", JSON.stringify(validation.reasons)); const workspace = evaluateWorkspaceModelProviderRegistry({ projectRegistry: projectRegistry("forbidden", dataRegion), modelProviderRegistry: registry }); assert.equal(workspace.projectRegistryDecision?.verdict, "allow", JSON.stringify(workspace.projectRegistryDecision?.reasons)); assert.equal(workspace.verdict, "allow", JSON.stringify(workspace.reasons)); const route = resolveModelInvocationRoute(routeInput("forbidden", registry, [], dataRegion)); assert.equal(route.verdict, "allow", JSON.stringify(route.reasons)); assert.equal(route.routePlan?.projectDataRegion, dataRegion); const missing = resolveModelInvocationRoute(routeInput("forbidden", providerRegistry(), [], dataRegion)); assert.equal(missing.verdict, "deny"); assert.ok(codes(missing).includes("region_not_supported")); assert.ok(codes(missing).includes("no_eligible_route")); assert.equal(missing.routePlan, null); });
test("messages is mandatory for every tool-free AI-022 invocation route", () => { const registry = providerRegistry({ providers: [provider("provider-local", "local", ["forbidden"], { capabilities: [] })], deployments: [deployment("deployment-local", "provider-local", { capabilities: [] })], modelProfiles: [profile("model-shared", undefined, { requiredCapabilities: [] }), profile("model-one", undefined, { requiredCapabilities: [] })] }); const decision = resolveModelInvocationRoute(routeInput("forbidden", registry, [], "eu", [])); assert.equal(decision.invocationAdmissionDecision?.verdict, "allow"); assert.ok((decision.invocationAdmissionDecision?.normalizedRequest?.messages.length ?? 0) > 0); assert.equal(decision.verdict, "deny"); assert.ok(codes(decision).includes("capability_not_supported")); assert.ok(codes(decision).includes("no_eligible_route")); assert.equal(decision.routePlan, null); });
test("messages missing only from Provider or Deployment fails closed", () => { const providerMissing = providerRegistry({ providers: [provider("provider-local", "local", ["forbidden"], { capabilities: [] })], deployments: [deployment("deployment-local", "provider-local", { capabilities: ["messages"] })], modelProfiles: [profile("model-shared", undefined, { requiredCapabilities: [] }), profile("model-one", undefined, { requiredCapabilities: [] })] }); const providerDecision = resolveModelInvocationRoute(routeInput("forbidden", providerMissing, [], "eu", [])); assert.equal(providerDecision.verdict, "deny"); assert.ok(codes(providerDecision).includes("capability_not_supported")); assert.equal(providerDecision.routePlan, null); const deploymentMissing = providerRegistry({ providers: [provider("provider-local", "local", ["forbidden"], { capabilities: ["messages"] })], deployments: [deployment("deployment-local", "provider-local", { capabilities: [] })], modelProfiles: [profile("model-shared", undefined, { requiredCapabilities: [] }), profile("model-one", undefined, { requiredCapabilities: [] })] }); const deploymentDecision = resolveModelInvocationRoute(routeInput("forbidden", deploymentMissing, [], "eu", [])); assert.equal(deploymentDecision.verdict, "deny"); assert.ok(codes(deploymentDecision).includes("capability_not_supported")); assert.ok(codes(deploymentDecision).includes("no_eligible_route")); assert.equal(deploymentDecision.routePlan, null); });
test("messages-compatible fallback becomes primary without mutating profile requirements", () => { const registry = providerRegistry({ providers: [provider("provider-a", "local", ["forbidden"], { capabilities: [] }), provider("provider-b", "local", ["forbidden"], { capabilities: ["messages"] })], deployments: [deployment("deployment-a", "provider-a", { capabilities: [] }), deployment("deployment-b", "provider-b", { capabilities: ["messages"] })], modelProfiles: [profile("model-shared", [{ deploymentId: "deployment-a", priority: 1 }, { deploymentId: "deployment-b", priority: 2 }], { requiredCapabilities: [] }), profile("model-one", [{ deploymentId: "deployment-b", priority: 1 }], { requiredCapabilities: [] })] }); const before = clone(registry); const decision = resolveModelInvocationRoute(routeInput("forbidden", registry, [], "eu", [])); assert.equal(decision.verdict, "allow", JSON.stringify(decision.reasons)); assert.equal(decision.routePlan?.primary.deploymentId, "deployment-b"); assert.deepEqual(registry, before); assert.deepEqual((registry.modelProfiles[0] as any).requiredCapabilities, []); });
test("redacted and approved remote routes carry planning requirements", () => { for (const [egress, requirement] of [["redacted_only", "redaction_required"], ["approved_minimum", "approval_required"]] as const) { const registry = providerRegistry({ providers: [provider("provider-remote", "remote", ["redacted_only", "approved_minimum"])], deployments: [deployment("deployment-remote", "provider-remote")], modelProfiles: [profile("model-shared", [{ deploymentId: "deployment-remote", priority: 1 }]), profile("model-one", [{ deploymentId: "deployment-remote", priority: 1 }])] }); const decision = resolveModelInvocationRoute(routeInput(egress, registry)); assert.equal(decision.verdict, "allow", JSON.stringify(decision.reasons)); assert.equal(decision.routePlan?.primary.dataHandlingRequirement, requirement); } });
test("remote candidate cannot route forbidden Project data", () => { const registry = providerRegistry({ providers: [provider("provider-remote", "remote", ["redacted_only", "approved_minimum"])], deployments: [deployment("deployment-remote", "provider-remote")], modelProfiles: [profile("model-shared", [{ deploymentId: "deployment-remote", priority: 1 }]), profile("model-one", [{ deploymentId: "deployment-remote", priority: 1 }])] }); const decision = resolveModelInvocationRoute(routeInput("forbidden", registry)); assert.equal(decision.verdict, "deny"); assert.equal(decision.routePlan, null); assert.ok(codes(decision).includes("data_egress_not_supported")); assert.ok(codes(decision).includes("no_eligible_route")); });
test("inactive primary is skipped and the active fallback becomes primary deterministically", () => { const registry = providerRegistry({ providers: [provider("provider-a"), provider("provider-b")], deployments: [deployment("deployment-a", "provider-a", { status: "paused" }), deployment("deployment-b", "provider-b")], modelProfiles: [profile("model-shared", [{ deploymentId: "deployment-b", priority: 2 }, { deploymentId: "deployment-a", priority: 1 }]), profile("model-one", [{ deploymentId: "deployment-b", priority: 1 }])] }); const decision = resolveModelInvocationRoute(routeInput("forbidden", registry)); assert.equal(decision.verdict, "allow", JSON.stringify(decision.reasons)); assert.equal(decision.routePlan?.primary.deploymentId, "deployment-b"); assert.deepEqual(decision.routePlan?.fallbacks, []); });
test("all unavailable candidates deny with no partial route", () => { const registry = providerRegistry({ providers: [provider("provider-local", "local", ["forbidden"], { status: "paused" })] }); const decision = resolveModelInvocationRoute(routeInput("forbidden", registry)); assert.equal(decision.verdict, "deny"); assert.equal(decision.routePlan, null); assert.ok(codes(decision).includes("provider_inactive")); assert.ok(codes(decision).includes("no_eligible_route")); });
test("region, tools, and output capability checks are factual and fail closed", () => { const region = projectRegistry() as any; region.projects[0].projectManifest.dataRegion = "us"; const regionInput = routeInput() as any; regionInput.projectRegistry = region; assert.ok(codes(resolveModelInvocationRoute(regionInput)).includes("region_not_supported")); const noTools = providerRegistry({ providers: [provider("provider-local", "local", ["forbidden"], { capabilities: ["messages", "structured_output"] })], deployments: [deployment("deployment-local", "provider-local", { capabilities: ["messages", "structured_output"] })], modelProfiles: [profile("model-shared", [{ deploymentId: "deployment-local", priority: 1 }], { requiredCapabilities: ["messages"] }), profile("model-one", [{ deploymentId: "deployment-local", priority: 1 }], { requiredCapabilities: ["messages"] })] }); assert.ok(codes(resolveModelInvocationRoute(routeInput("forbidden", noTools))).includes("tools_not_supported")); });
test("Project version mismatch is detected after factual prerequisite allows", () => { const input = routeInput() as any; input.projectRegistry.projects[0].projectManifest.version = 4; const decision = resolveModelInvocationRoute(input); assert.ok(codes(decision).includes("project_version_mismatch")); assert.equal(decision.projectRegistryDecision?.verdict, "allow"); assert.equal(decision.invocationAdmissionDecision?.verdict, "allow"); assert.equal(decision.routePlan, null); });
test("real AI-022 idempotent admission resolves and preserves the factual request", () => { const snapshot = runningSnapshot(); const first = evaluateModelInvocationAdmission({ snapshot, draft: draft(), existingRequests: [] }); assert.equal(first.verdict, "allow"); assert.ok(first.normalizedRequest); const input = { projectRegistry: projectRegistry(), modelProviderRegistry: providerRegistry(), invocationAdmission: { snapshot, draft: draft(), existingRequests: [first.normalizedRequest] } }; const decision = resolveModelInvocationRoute(input); assert.equal(decision.verdict, "allow", JSON.stringify(decision.reasons)); assert.equal(decision.invocationAdmissionDecision?.verdict, "idempotent"); assert.equal(decision.routePlan?.invocationId, first.normalizedRequest.invocationId); });
test("real AI-022 deny wins before provider registry validation and leaves no partial outputs", () => { const decision = resolveModelInvocationRoute({ projectRegistry: projectRegistry(), modelProviderRegistry: {}, invocationAdmission: { snapshot: runningSnapshot(), draft: { ...draft(), stepId: "missing-step" }, existingRequests: [] } }); assert.deepEqual(codes(decision), ["invalid_invocation_admission"]); assert.equal(decision.invocationAdmissionDecision?.verdict, "deny"); assert.equal(decision.normalizedRegistry, null); assert.equal(decision.routePlan, null); });
test("exact inactive modelProfile never falls back by provider kind or another profile", () => { const registry = providerRegistry(); (registry.modelProfiles[0] as any).status = "paused"; const decision = resolveModelInvocationRoute(routeInput("forbidden", registry)); assert.equal(decision.verdict, "deny"); assert.ok(codes(decision).includes("model_profile_inactive")); assert.equal(decision.routePlan, null); });
test("route resolution is repeated deterministic, reverse-order invariant, fresh, and deeply frozen", () => { const registry = providerRegistry({ providers: [provider("provider-a"), provider("provider-b")], deployments: [deployment("deployment-a", "provider-a"), deployment("deployment-b", "provider-b")], modelProfiles: [profile("model-shared", [{ deploymentId: "deployment-b", priority: 2 }, { deploymentId: "deployment-a", priority: 1 }]), profile("model-one", [{ deploymentId: "deployment-a", priority: 1 }])] }); const input = routeInput("forbidden", registry); const first = resolveModelInvocationRoute(input); const second = resolveModelInvocationRoute(input); assert.deepEqual(second, first); assert.notEqual(second.routePlan, first.routePlan); const reversed = clone(registry) as any; reversed.providers.reverse(); reversed.deployments.reverse(); reversed.modelProfiles.reverse(); for (const item of reversed.modelProfiles) item.candidates.reverse(); assert.deepEqual(resolveModelInvocationRoute(routeInput("forbidden", reversed)), first); assert.equal(deeplyFrozen(first), true); });
test("route envelope rejects accessors, cycles, Set, sparse arrays, and absolute depth without throw", () => { const values: unknown[] = []; const accessor = { projectRegistry: projectRegistry(), modelProviderRegistry: providerRegistry() }; Object.defineProperty(accessor, "invocationAdmission", { enumerable: true, get() { throw new Error("no"); } }); values.push(accessor); const cycle: any = routeInput(); cycle.loop = cycle; values.push(cycle, new Set(), { projectRegistry: projectRegistry(), modelProviderRegistry: providerRegistry(), invocationAdmission: { snapshot: runningSnapshot(), draft: draft(), existingRequests: Array(2) } }); let deep: any = {}; const root = deep; for (let index = 0; index < modelProviderRegistryLimits.maxEnvelopeDepth + 2; index += 1) { deep.next = {}; deep = deep.next; } values.push(root); for (const value of values) { assert.doesNotThrow(() => resolveModelInvocationRoute(value)); const decision = resolveModelInvocationRoute(value); assert.equal(decision.verdict, "deny"); assert.equal(decision.routePlan, null); } });
